//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Data/PlayerControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace TetrisTower.Game
{
    public partial class @PlayerControls : IInputActionCollection2, IDisposable
    {
        public InputActionAsset asset { get; }
        public @PlayerControls()
        {
            asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerControls"",
    ""maps"": [
        {
            ""name"": ""TowerLevelPlay"",
            ""id"": ""9cb11c57-6035-4442-b6b4-fb85c51dc04a"",
            ""actions"": [
                {
                    ""name"": ""MoveShapeLeft"",
                    ""type"": ""Button"",
                    ""id"": ""c42aaa47-96d2-4c31-b0c7-5be28c1a25df"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MoveShapeRight"",
                    ""type"": ""Button"",
                    ""id"": ""5bdcd5dc-047d-4593-96a8-d27f7fd530e6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RotateShapeUp"",
                    ""type"": ""Button"",
                    ""id"": ""12911e7a-7981-40c1-83b9-9342bd21583f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RotateShapeDown"",
                    ""type"": ""Button"",
                    ""id"": ""d2ca85d2-bb09-4e02-8dce-d151895698da"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""FallSpeedUp"",
                    ""type"": ""Button"",
                    ""id"": ""7ad6e614-2658-40c7-932a-9d41693753b3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Pointer-FallSpeedUp"",
                    ""type"": ""PassThrough"",
                    ""id"": ""262069d4-7042-4ac7-a47f-46cec272d1c9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Pointer-Press"",
                    ""type"": ""PassThrough"",
                    ""id"": ""1ea63dad-8fe3-4d3e-8e95-8ba8c2e56623"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""05f6913d-c316-48b2-a6bb-e225f14c7960"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard&Mouse"",
                    ""action"": ""FallSpeedUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fbd6776d-cc85-48bb-962b-3b856376eaa9"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard&Mouse"",
                    ""action"": ""FallSpeedUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b89000c4-6b25-4e79-bfa9-46186462a044"",
                    ""path"": ""<Keyboard>/numpadEnter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""FallSpeedUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""143bb1cd-cc10-4eca-a2f0-a3664166fe91"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""FallSpeedUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7f921f31-a271-4435-bee3-f8ebf3b5a101"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""MoveShapeLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e90a1de5-f1aa-41be-a56b-90f4b7fa3c09"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""MoveShapeLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fccaa75c-6162-4e57-9452-308311e09c5b"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""MoveShapeLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4c7376a0-a019-4e59-ab10-a13dda1bf8cd"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""MoveShapeRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4fab62e1-b2fa-4bb5-ad59-b25e6e31a04e"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""MoveShapeRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3bad19e9-17e9-4fb6-9728-219fb1d017e2"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""MoveShapeRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""948d3740-9b93-40c0-97a5-0308b3036a65"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""RotateShapeUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""25a29330-7f1e-4e20-9ff9-442f497d7f3f"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""RotateShapeUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a2fb49a3-b61b-4942-8d6f-26fdb3e979a6"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""RotateShapeUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ba3aa4a0-29fa-4d70-9fad-7a2c7cc5b260"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""RotateShapeDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8b02350e-fce8-4d19-85c7-80ccc43b7d3b"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""RotateShapeDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6b97bb9e-2c32-4ea2-9248-e04b2ac7fdbd"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""RotateShapeDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1729467b-c02e-4277-b198-5fc6e0903220"",
                    ""path"": ""<Pointer>/press"",
                    ""interactions"": ""MultiTap"",
                    ""processors"": """",
                    ""groups"": ""Touch;Keyboard&Mouse"",
                    ""action"": ""Pointer-FallSpeedUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b55cdccc-bc3a-4777-a170-e9934bbd406a"",
                    ""path"": ""<Pointer>/press"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse;Touch"",
                    ""action"": ""Pointer-Press"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""TowerLevelPaused"",
            ""id"": ""8e96621b-511e-4f34-840f-669ae8e49f79"",
            ""actions"": [],
            ""bindings"": []
        },
        {
            ""name"": ""WorldMapPlay"",
            ""id"": ""5c59a694-57da-4fbc-a198-41217f89a9fe"",
            ""actions"": [
                {
                    ""name"": ""DiscworldMovement"",
                    ""type"": ""Value"",
                    ""id"": ""aecc3542-ed9c-4b85-b7f5-d1207b9751ec"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""DiscworldZoom"",
                    ""type"": ""Value"",
                    ""id"": ""21620832-1507-4a6f-8253-4195517531c3"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Pointer-Press"",
                    ""type"": ""PassThrough"",
                    ""id"": ""0bece59f-a184-4b66-b8c6-3601d1e347fe"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Pointer-Click"",
                    ""type"": ""PassThrough"",
                    ""id"": ""3954e8ac-f530-46cc-988c-f1b39378d525"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""AllArrows"",
                    ""id"": ""e75e626a-3ad8-4546-9dd1-dc27c80a1a97"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DiscworldMovement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""b60cd065-9012-4072-a9b9-086516c33290"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""DiscworldMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""ee57cd21-ce12-414f-a07a-3d4fb64318e0"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""DiscworldMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""1dc44a42-fd04-4ae7-b7dd-22429241bb23"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""DiscworldMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""85087891-c1fc-40a9-a0a8-a2ae59553c31"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""DiscworldMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""WASD"",
                    ""id"": ""ff49a862-b3b1-4001-b5ca-6f2b4ede73bb"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DiscworldMovement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""0d8dcfc6-cb7b-4c1b-acb6-202ab41d9826"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""DiscworldMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""f61ef91b-6c9d-49aa-8ed7-e92ffccfbbdc"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""DiscworldMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""59659b5c-4cd2-4ee6-bdd9-bb1bf420edfd"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""DiscworldMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""d5b5a74b-0724-443a-b47b-c36c628eae9c"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""DiscworldMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""a99add60-7c3c-42c9-a793-8726d546fe7a"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""DiscworldMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""97d5ff08-4168-423c-bfd0-d4da0bde5d2a"",
                    ""path"": ""<Pointer>/press"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse;Touch"",
                    ""action"": ""Pointer-Press"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""PageUpDown"",
                    ""id"": ""89a70858-72e3-41a9-9bae-ff0ffc120c2c"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DiscworldZoom"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""9f2a77b0-5fa0-4355-b434-fa70ccfdf9ea"",
                    ""path"": ""<Keyboard>/pageUp"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""DiscworldZoom"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""6c6ff859-a656-415e-bd74-92ebfb644c20"",
                    ""path"": ""<Keyboard>/pageDown"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""DiscworldZoom"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""PlusMinus"",
                    ""id"": ""125d4cfe-3ec0-40fa-b8c8-bb8239300c04"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DiscworldZoom"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""987e3206-91c6-41dd-817c-dc1455f41b2f"",
                    ""path"": ""<Keyboard>/numpadMinus"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""DiscworldZoom"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""a98e73a6-7667-4595-98f1-7fe0912ead1f"",
                    ""path"": ""<Keyboard>/numpadPlus"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""DiscworldZoom"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""ScrollWheel"",
                    ""id"": ""9593e15b-365c-4b82-808e-9a598ff297ac"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": ""Scale(factor=0.15)"",
                    ""groups"": """",
                    ""action"": ""DiscworldZoom"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""99465a15-fef7-4352-814a-416cd8a15884"",
                    ""path"": ""<Mouse>/scroll/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""DiscworldZoom"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""df5b11ac-0638-49d1-8bcb-28f05307f42f"",
                    ""path"": ""<Mouse>/scroll/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""DiscworldZoom"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""QE"",
                    ""id"": ""644b0674-7723-4bff-9513-5331f73371c2"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DiscworldZoom"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""8c4e3327-1e63-4830-9816-e75943b754f5"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""DiscworldZoom"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""f61d4837-64f6-4eec-927a-e80caeac4fc4"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""DiscworldZoom"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Triggers"",
                    ""id"": ""612c25ae-0ffa-464c-ba04-67a51dc911e3"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DiscworldZoom"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""28ee870e-bcda-44bc-b874-0be923f1f3ec"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""DiscworldZoom"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""1d8985eb-4a00-4373-aa9b-7b0a49864ea7"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""DiscworldZoom"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""57a658c0-3566-407c-a8c1-ea950dcc39ce"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": ""Tap"",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Pointer-Click"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bbd73af6-2550-4721-945a-f5c30e6aa56a"",
                    ""path"": ""<Pen>/tip"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Pointer-Click"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d59e2c18-309c-4dc0-9440-7432d88f405f"",
                    ""path"": ""<Touchscreen>/touch*/press"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Touch"",
                    ""action"": ""Pointer-Click"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""WorldMapPaused"",
            ""id"": ""913315cb-b9b2-476f-b22b-cc6806bf6d06"",
            ""actions"": [],
            ""bindings"": []
        },
        {
            ""name"": ""LevelsShared"",
            ""id"": ""31910e90-aaf6-4365-8ae6-f48836710769"",
            ""actions"": [
                {
                    ""name"": ""ToggleMenu"",
                    ""type"": ""Button"",
                    ""id"": ""36ad07ff-2f06-4744-84c1-304f39e36653"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""4a743f81-f59c-4d7e-93a2-5b6bd79836a3"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""ToggleMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7f3db0ba-a088-416e-9fd5-c7e03fc19609"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""ToggleMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7622fb5c-346c-48a9-83e5-230709c3d7b1"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""ToggleMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""UI"",
            ""id"": ""36699a9d-0fc8-428a-941c-cd7c0d64be36"",
            ""actions"": [
                {
                    ""name"": ""Navigate"",
                    ""type"": ""PassThrough"",
                    ""id"": ""54525046-29d2-4cda-aaec-a9b82a378ec7"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Submit"",
                    ""type"": ""PassThrough"",
                    ""id"": ""279b44f2-1205-4c28-b887-362c4943c659"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Cancel"",
                    ""type"": ""PassThrough"",
                    ""id"": ""dcea39f7-1e91-4a47-9e1d-a65ca4cd0e06"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Point"",
                    ""type"": ""PassThrough"",
                    ""id"": ""ad9e3e2f-9e9a-45e9-99ee-8b5cdc9c4f35"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Click"",
                    ""type"": ""PassThrough"",
                    ""id"": ""2be8c320-66bd-4c7d-928e-3b58efec8203"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ScrollWheel"",
                    ""type"": ""PassThrough"",
                    ""id"": ""b7ba00c9-cd6e-428c-b724-11b6ec118b42"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MiddleClick"",
                    ""type"": ""PassThrough"",
                    ""id"": ""98a7491d-0609-49ac-aa6d-b8ebb3518e89"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightClick"",
                    ""type"": ""PassThrough"",
                    ""id"": ""9eaf26e4-8d08-406c-aba9-1318e475f693"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TrackedDevicePosition"",
                    ""type"": ""PassThrough"",
                    ""id"": ""dc03e0d8-fd60-4eda-87e9-e73abdf8057b"",
                    ""expectedControlType"": ""Vector3"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TrackedDeviceOrientation"",
                    ""type"": ""PassThrough"",
                    ""id"": ""90d54a8c-9c4d-47ec-9510-e5322715eff2"",
                    ""expectedControlType"": ""Quaternion"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""Gamepad"",
                    ""id"": ""809f371f-c5e2-4e7a-83a1-d867598f40dd"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigate"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""14a5d6e8-4aaf-4119-a9ef-34b8c2c548bf"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""up"",
                    ""id"": ""9144cbe6-05e1-4687-a6d7-24f99d23dd81"",
                    ""path"": ""<Gamepad>/rightStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""2db08d65-c5fb-421b-983f-c71163608d67"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""58748904-2ea9-4a80-8579-b500e6a76df8"",
                    ""path"": ""<Gamepad>/rightStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""8ba04515-75aa-45de-966d-393d9bbd1c14"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""712e721c-bdfb-4b23-a86c-a0d9fcfea921"",
                    ""path"": ""<Gamepad>/rightStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""fcd248ae-a788-4676-a12e-f4d81205600b"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""1f04d9bc-c50b-41a1-bfcc-afb75475ec20"",
                    ""path"": ""<Gamepad>/rightStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""fb8277d4-c5cd-4663-9dc7-ee3f0b506d90"",
                    ""path"": ""<Gamepad>/dpad"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Joystick"",
                    ""id"": ""e25d9774-381c-4a61-b47c-7b6b299ad9f9"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigate"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Keyboard"",
                    ""id"": ""ff527021-f211-4c02-933e-5976594c46ed"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigate"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""563fbfdd-0f09-408d-aa75-8642c4f08ef0"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""up"",
                    ""id"": ""eb480147-c587-4a33-85ed-eb0ab9942c43"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""2bf42165-60bc-42ca-8072-8c13ab40239b"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""85d264ad-e0a0-4565-b7ff-1a37edde51ac"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""74214943-c580-44e4-98eb-ad7eebe17902"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""cea9b045-a000-445b-95b8-0c171af70a3b"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""8607c725-d935-4808-84b1-8354e29bab63"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""4cda81dc-9edd-4e03-9d7c-a71a14345d0b"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""9e92bb26-7e3b-4ec4-b06b-3c8f8e498ddc"",
                    ""path"": ""*/{Submit}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad;Keyboard&Mouse;Touch"",
                    ""action"": ""Submit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""82627dcc-3b13-4ba9-841d-e4b746d6553e"",
                    ""path"": ""*/{Cancel}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Touch;Gamepad;Keyboard&Mouse"",
                    ""action"": ""Cancel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c52c8e0b-8179-41d3-b8a1-d149033bbe86"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Point"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e1394cbc-336e-44ce-9ea8-6007ed6193f7"",
                    ""path"": ""<Pen>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Point"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5693e57a-238a-46ed-b5ae-e64e6e574302"",
                    ""path"": ""<Touchscreen>/touch*/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Touch"",
                    ""action"": ""Point"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4faf7dc9-b979-4210-aa8c-e808e1ef89f5"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard&Mouse"",
                    ""action"": ""Click"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8d66d5ba-88d7-48e6-b1cd-198bbfef7ace"",
                    ""path"": ""<Pen>/tip"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard&Mouse"",
                    ""action"": ""Click"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""47c2a644-3ebc-4dae-a106-589b7ca75b59"",
                    ""path"": ""<Touchscreen>/touch*/press"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Touch"",
                    ""action"": ""Click"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""38c99815-14ea-4617-8627-164d27641299"",
                    ""path"": ""<Mouse>/scroll"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard&Mouse"",
                    ""action"": ""ScrollWheel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""24066f69-da47-44f3-a07e-0015fb02eb2e"",
                    ""path"": ""<Mouse>/middleButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard&Mouse"",
                    ""action"": ""MiddleClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4c191405-5738-4d4b-a523-c6a301dbf754"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard&Mouse"",
                    ""action"": ""RightClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""CommonHotkeys"",
            ""id"": ""c0dd4bb8-b434-48e5-bcd8-e3f6590ba5c9"",
            ""actions"": [
                {
                    ""name"": ""Back"",
                    ""type"": ""Button"",
                    ""id"": ""3bbe5692-1874-443b-93f6-cb8a7eea718a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Confirm"",
                    ""type"": ""Button"",
                    ""id"": ""dd40e659-2525-4a8c-a56d-9e5ce74051a1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""NextSection"",
                    ""type"": ""Button"",
                    ""id"": ""3abb3d3f-b486-4f63-abe0-f795fb1342cd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PrevSection"",
                    ""type"": ""Button"",
                    ""id"": ""3ea85ef3-5f21-4ad3-a0c8-31b003bd8a53"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PickerNext"",
                    ""type"": ""Button"",
                    ""id"": ""4eccd0ff-b7a8-4640-ab21-160db0ef0b22"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PickerPrev"",
                    ""type"": ""Button"",
                    ""id"": ""84055c8f-853b-4919-9759-b3dbb9ff8bfa"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""11b0552b-44df-4cc7-acd5-bf6c669f5c22"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Back"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""46062f62-4509-4337-ab88-cafdae202cdf"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Back"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0e856c71-d343-443e-9761-dd29c3282071"",
                    ""path"": ""*/{Back}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad;Keyboard&Mouse"",
                    ""action"": ""Back"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c9264633-0d18-4c29-a1ad-34bda9ec34fb"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Confirm"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1744cc73-c376-483c-9a2d-832ae0cf6636"",
                    ""path"": ""<Keyboard>/numpadEnter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Confirm"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""589d6359-788e-4ce2-bebd-99f58690a87b"",
                    ""path"": ""*/{Submit}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad;Keyboard&Mouse"",
                    ""action"": ""Confirm"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ba42f8fa-228c-48bc-acc5-94c9a59f7e5e"",
                    ""path"": ""<Keyboard>/rightBracket"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""NextSection"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""70a8a5fd-1eda-43af-a842-7bb55d332651"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""NextSection"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""62ae90ce-9021-4feb-b5d4-4c84912b8f00"",
                    ""path"": ""<Keyboard>/leftBracket"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""PrevSection"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ef978be4-7a5e-4298-858a-d8131888dae3"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""PrevSection"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3a2a6814-4ef5-41b1-8af3-940af308987d"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""PickerNext"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bd64676c-7f72-4296-8d84-ec2929974cd0"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""PickerNext"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fe5a4b85-e571-4c34-ab66-3b000252d463"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""PickerNext"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5c1b6ea1-9604-4b3c-a676-db78303eaa1e"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""PickerNext"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""27a656f6-9cd1-42c8-ad85-6e91b3f7b443"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""PickerPrev"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9bb8e6da-910a-4aa0-b7da-77159acc050f"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""PickerPrev"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7b9ee5fe-7685-4292-aee8-a75fdd113808"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""PickerPrev"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9cab4c78-57c5-4130-b611-570e9d66edc9"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""PickerPrev"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Keyboard&Mouse"",
            ""bindingGroup"": ""Keyboard&Mouse"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Gamepad"",
            ""bindingGroup"": ""Gamepad"",
            ""devices"": [
                {
                    ""devicePath"": ""<Gamepad>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Touch"",
            ""bindingGroup"": ""Touch"",
            ""devices"": [
                {
                    ""devicePath"": ""<Touchscreen>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
            // TowerLevelPlay
            m_TowerLevelPlay = asset.FindActionMap("TowerLevelPlay", throwIfNotFound: true);
            m_TowerLevelPlay_MoveShapeLeft = m_TowerLevelPlay.FindAction("MoveShapeLeft", throwIfNotFound: true);
            m_TowerLevelPlay_MoveShapeRight = m_TowerLevelPlay.FindAction("MoveShapeRight", throwIfNotFound: true);
            m_TowerLevelPlay_RotateShapeUp = m_TowerLevelPlay.FindAction("RotateShapeUp", throwIfNotFound: true);
            m_TowerLevelPlay_RotateShapeDown = m_TowerLevelPlay.FindAction("RotateShapeDown", throwIfNotFound: true);
            m_TowerLevelPlay_FallSpeedUp = m_TowerLevelPlay.FindAction("FallSpeedUp", throwIfNotFound: true);
            m_TowerLevelPlay_PointerFallSpeedUp = m_TowerLevelPlay.FindAction("Pointer-FallSpeedUp", throwIfNotFound: true);
            m_TowerLevelPlay_PointerPress = m_TowerLevelPlay.FindAction("Pointer-Press", throwIfNotFound: true);
            // TowerLevelPaused
            m_TowerLevelPaused = asset.FindActionMap("TowerLevelPaused", throwIfNotFound: true);
            // WorldMapPlay
            m_WorldMapPlay = asset.FindActionMap("WorldMapPlay", throwIfNotFound: true);
            m_WorldMapPlay_DiscworldMovement = m_WorldMapPlay.FindAction("DiscworldMovement", throwIfNotFound: true);
            m_WorldMapPlay_DiscworldZoom = m_WorldMapPlay.FindAction("DiscworldZoom", throwIfNotFound: true);
            m_WorldMapPlay_PointerPress = m_WorldMapPlay.FindAction("Pointer-Press", throwIfNotFound: true);
            m_WorldMapPlay_PointerClick = m_WorldMapPlay.FindAction("Pointer-Click", throwIfNotFound: true);
            // WorldMapPaused
            m_WorldMapPaused = asset.FindActionMap("WorldMapPaused", throwIfNotFound: true);
            // LevelsShared
            m_LevelsShared = asset.FindActionMap("LevelsShared", throwIfNotFound: true);
            m_LevelsShared_ToggleMenu = m_LevelsShared.FindAction("ToggleMenu", throwIfNotFound: true);
            // UI
            m_UI = asset.FindActionMap("UI", throwIfNotFound: true);
            m_UI_Navigate = m_UI.FindAction("Navigate", throwIfNotFound: true);
            m_UI_Submit = m_UI.FindAction("Submit", throwIfNotFound: true);
            m_UI_Cancel = m_UI.FindAction("Cancel", throwIfNotFound: true);
            m_UI_Point = m_UI.FindAction("Point", throwIfNotFound: true);
            m_UI_Click = m_UI.FindAction("Click", throwIfNotFound: true);
            m_UI_ScrollWheel = m_UI.FindAction("ScrollWheel", throwIfNotFound: true);
            m_UI_MiddleClick = m_UI.FindAction("MiddleClick", throwIfNotFound: true);
            m_UI_RightClick = m_UI.FindAction("RightClick", throwIfNotFound: true);
            m_UI_TrackedDevicePosition = m_UI.FindAction("TrackedDevicePosition", throwIfNotFound: true);
            m_UI_TrackedDeviceOrientation = m_UI.FindAction("TrackedDeviceOrientation", throwIfNotFound: true);
            // CommonHotkeys
            m_CommonHotkeys = asset.FindActionMap("CommonHotkeys", throwIfNotFound: true);
            m_CommonHotkeys_Back = m_CommonHotkeys.FindAction("Back", throwIfNotFound: true);
            m_CommonHotkeys_Confirm = m_CommonHotkeys.FindAction("Confirm", throwIfNotFound: true);
            m_CommonHotkeys_NextSection = m_CommonHotkeys.FindAction("NextSection", throwIfNotFound: true);
            m_CommonHotkeys_PrevSection = m_CommonHotkeys.FindAction("PrevSection", throwIfNotFound: true);
            m_CommonHotkeys_PickerNext = m_CommonHotkeys.FindAction("PickerNext", throwIfNotFound: true);
            m_CommonHotkeys_PickerPrev = m_CommonHotkeys.FindAction("PickerPrev", throwIfNotFound: true);
        }

        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        public void Enable()
        {
            asset.Enable();
        }

        public void Disable()
        {
            asset.Disable();
        }
        public IEnumerable<InputBinding> bindings => asset.bindings;

        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }
        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // TowerLevelPlay
        private readonly InputActionMap m_TowerLevelPlay;
        private ITowerLevelPlayActions m_TowerLevelPlayActionsCallbackInterface;
        private readonly InputAction m_TowerLevelPlay_MoveShapeLeft;
        private readonly InputAction m_TowerLevelPlay_MoveShapeRight;
        private readonly InputAction m_TowerLevelPlay_RotateShapeUp;
        private readonly InputAction m_TowerLevelPlay_RotateShapeDown;
        private readonly InputAction m_TowerLevelPlay_FallSpeedUp;
        private readonly InputAction m_TowerLevelPlay_PointerFallSpeedUp;
        private readonly InputAction m_TowerLevelPlay_PointerPress;
        public struct TowerLevelPlayActions
        {
            private @PlayerControls m_Wrapper;
            public TowerLevelPlayActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
            public InputAction @MoveShapeLeft => m_Wrapper.m_TowerLevelPlay_MoveShapeLeft;
            public InputAction @MoveShapeRight => m_Wrapper.m_TowerLevelPlay_MoveShapeRight;
            public InputAction @RotateShapeUp => m_Wrapper.m_TowerLevelPlay_RotateShapeUp;
            public InputAction @RotateShapeDown => m_Wrapper.m_TowerLevelPlay_RotateShapeDown;
            public InputAction @FallSpeedUp => m_Wrapper.m_TowerLevelPlay_FallSpeedUp;
            public InputAction @PointerFallSpeedUp => m_Wrapper.m_TowerLevelPlay_PointerFallSpeedUp;
            public InputAction @PointerPress => m_Wrapper.m_TowerLevelPlay_PointerPress;
            public InputActionMap Get() { return m_Wrapper.m_TowerLevelPlay; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(TowerLevelPlayActions set) { return set.Get(); }
            public void SetCallbacks(ITowerLevelPlayActions instance)
            {
                if (m_Wrapper.m_TowerLevelPlayActionsCallbackInterface != null)
                {
                    @MoveShapeLeft.started -= m_Wrapper.m_TowerLevelPlayActionsCallbackInterface.OnMoveShapeLeft;
                    @MoveShapeLeft.performed -= m_Wrapper.m_TowerLevelPlayActionsCallbackInterface.OnMoveShapeLeft;
                    @MoveShapeLeft.canceled -= m_Wrapper.m_TowerLevelPlayActionsCallbackInterface.OnMoveShapeLeft;
                    @MoveShapeRight.started -= m_Wrapper.m_TowerLevelPlayActionsCallbackInterface.OnMoveShapeRight;
                    @MoveShapeRight.performed -= m_Wrapper.m_TowerLevelPlayActionsCallbackInterface.OnMoveShapeRight;
                    @MoveShapeRight.canceled -= m_Wrapper.m_TowerLevelPlayActionsCallbackInterface.OnMoveShapeRight;
                    @RotateShapeUp.started -= m_Wrapper.m_TowerLevelPlayActionsCallbackInterface.OnRotateShapeUp;
                    @RotateShapeUp.performed -= m_Wrapper.m_TowerLevelPlayActionsCallbackInterface.OnRotateShapeUp;
                    @RotateShapeUp.canceled -= m_Wrapper.m_TowerLevelPlayActionsCallbackInterface.OnRotateShapeUp;
                    @RotateShapeDown.started -= m_Wrapper.m_TowerLevelPlayActionsCallbackInterface.OnRotateShapeDown;
                    @RotateShapeDown.performed -= m_Wrapper.m_TowerLevelPlayActionsCallbackInterface.OnRotateShapeDown;
                    @RotateShapeDown.canceled -= m_Wrapper.m_TowerLevelPlayActionsCallbackInterface.OnRotateShapeDown;
                    @FallSpeedUp.started -= m_Wrapper.m_TowerLevelPlayActionsCallbackInterface.OnFallSpeedUp;
                    @FallSpeedUp.performed -= m_Wrapper.m_TowerLevelPlayActionsCallbackInterface.OnFallSpeedUp;
                    @FallSpeedUp.canceled -= m_Wrapper.m_TowerLevelPlayActionsCallbackInterface.OnFallSpeedUp;
                    @PointerFallSpeedUp.started -= m_Wrapper.m_TowerLevelPlayActionsCallbackInterface.OnPointerFallSpeedUp;
                    @PointerFallSpeedUp.performed -= m_Wrapper.m_TowerLevelPlayActionsCallbackInterface.OnPointerFallSpeedUp;
                    @PointerFallSpeedUp.canceled -= m_Wrapper.m_TowerLevelPlayActionsCallbackInterface.OnPointerFallSpeedUp;
                    @PointerPress.started -= m_Wrapper.m_TowerLevelPlayActionsCallbackInterface.OnPointerPress;
                    @PointerPress.performed -= m_Wrapper.m_TowerLevelPlayActionsCallbackInterface.OnPointerPress;
                    @PointerPress.canceled -= m_Wrapper.m_TowerLevelPlayActionsCallbackInterface.OnPointerPress;
                }
                m_Wrapper.m_TowerLevelPlayActionsCallbackInterface = instance;
                if (instance != null)
                {
                    @MoveShapeLeft.started += instance.OnMoveShapeLeft;
                    @MoveShapeLeft.performed += instance.OnMoveShapeLeft;
                    @MoveShapeLeft.canceled += instance.OnMoveShapeLeft;
                    @MoveShapeRight.started += instance.OnMoveShapeRight;
                    @MoveShapeRight.performed += instance.OnMoveShapeRight;
                    @MoveShapeRight.canceled += instance.OnMoveShapeRight;
                    @RotateShapeUp.started += instance.OnRotateShapeUp;
                    @RotateShapeUp.performed += instance.OnRotateShapeUp;
                    @RotateShapeUp.canceled += instance.OnRotateShapeUp;
                    @RotateShapeDown.started += instance.OnRotateShapeDown;
                    @RotateShapeDown.performed += instance.OnRotateShapeDown;
                    @RotateShapeDown.canceled += instance.OnRotateShapeDown;
                    @FallSpeedUp.started += instance.OnFallSpeedUp;
                    @FallSpeedUp.performed += instance.OnFallSpeedUp;
                    @FallSpeedUp.canceled += instance.OnFallSpeedUp;
                    @PointerFallSpeedUp.started += instance.OnPointerFallSpeedUp;
                    @PointerFallSpeedUp.performed += instance.OnPointerFallSpeedUp;
                    @PointerFallSpeedUp.canceled += instance.OnPointerFallSpeedUp;
                    @PointerPress.started += instance.OnPointerPress;
                    @PointerPress.performed += instance.OnPointerPress;
                    @PointerPress.canceled += instance.OnPointerPress;
                }
            }
        }
        public TowerLevelPlayActions @TowerLevelPlay => new TowerLevelPlayActions(this);

        // TowerLevelPaused
        private readonly InputActionMap m_TowerLevelPaused;
        private ITowerLevelPausedActions m_TowerLevelPausedActionsCallbackInterface;
        public struct TowerLevelPausedActions
        {
            private @PlayerControls m_Wrapper;
            public TowerLevelPausedActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
            public InputActionMap Get() { return m_Wrapper.m_TowerLevelPaused; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(TowerLevelPausedActions set) { return set.Get(); }
            public void SetCallbacks(ITowerLevelPausedActions instance)
            {
                if (m_Wrapper.m_TowerLevelPausedActionsCallbackInterface != null)
                {
                }
                m_Wrapper.m_TowerLevelPausedActionsCallbackInterface = instance;
                if (instance != null)
                {
                }
            }
        }
        public TowerLevelPausedActions @TowerLevelPaused => new TowerLevelPausedActions(this);

        // WorldMapPlay
        private readonly InputActionMap m_WorldMapPlay;
        private IWorldMapPlayActions m_WorldMapPlayActionsCallbackInterface;
        private readonly InputAction m_WorldMapPlay_DiscworldMovement;
        private readonly InputAction m_WorldMapPlay_DiscworldZoom;
        private readonly InputAction m_WorldMapPlay_PointerPress;
        private readonly InputAction m_WorldMapPlay_PointerClick;
        public struct WorldMapPlayActions
        {
            private @PlayerControls m_Wrapper;
            public WorldMapPlayActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
            public InputAction @DiscworldMovement => m_Wrapper.m_WorldMapPlay_DiscworldMovement;
            public InputAction @DiscworldZoom => m_Wrapper.m_WorldMapPlay_DiscworldZoom;
            public InputAction @PointerPress => m_Wrapper.m_WorldMapPlay_PointerPress;
            public InputAction @PointerClick => m_Wrapper.m_WorldMapPlay_PointerClick;
            public InputActionMap Get() { return m_Wrapper.m_WorldMapPlay; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(WorldMapPlayActions set) { return set.Get(); }
            public void SetCallbacks(IWorldMapPlayActions instance)
            {
                if (m_Wrapper.m_WorldMapPlayActionsCallbackInterface != null)
                {
                    @DiscworldMovement.started -= m_Wrapper.m_WorldMapPlayActionsCallbackInterface.OnDiscworldMovement;
                    @DiscworldMovement.performed -= m_Wrapper.m_WorldMapPlayActionsCallbackInterface.OnDiscworldMovement;
                    @DiscworldMovement.canceled -= m_Wrapper.m_WorldMapPlayActionsCallbackInterface.OnDiscworldMovement;
                    @DiscworldZoom.started -= m_Wrapper.m_WorldMapPlayActionsCallbackInterface.OnDiscworldZoom;
                    @DiscworldZoom.performed -= m_Wrapper.m_WorldMapPlayActionsCallbackInterface.OnDiscworldZoom;
                    @DiscworldZoom.canceled -= m_Wrapper.m_WorldMapPlayActionsCallbackInterface.OnDiscworldZoom;
                    @PointerPress.started -= m_Wrapper.m_WorldMapPlayActionsCallbackInterface.OnPointerPress;
                    @PointerPress.performed -= m_Wrapper.m_WorldMapPlayActionsCallbackInterface.OnPointerPress;
                    @PointerPress.canceled -= m_Wrapper.m_WorldMapPlayActionsCallbackInterface.OnPointerPress;
                    @PointerClick.started -= m_Wrapper.m_WorldMapPlayActionsCallbackInterface.OnPointerClick;
                    @PointerClick.performed -= m_Wrapper.m_WorldMapPlayActionsCallbackInterface.OnPointerClick;
                    @PointerClick.canceled -= m_Wrapper.m_WorldMapPlayActionsCallbackInterface.OnPointerClick;
                }
                m_Wrapper.m_WorldMapPlayActionsCallbackInterface = instance;
                if (instance != null)
                {
                    @DiscworldMovement.started += instance.OnDiscworldMovement;
                    @DiscworldMovement.performed += instance.OnDiscworldMovement;
                    @DiscworldMovement.canceled += instance.OnDiscworldMovement;
                    @DiscworldZoom.started += instance.OnDiscworldZoom;
                    @DiscworldZoom.performed += instance.OnDiscworldZoom;
                    @DiscworldZoom.canceled += instance.OnDiscworldZoom;
                    @PointerPress.started += instance.OnPointerPress;
                    @PointerPress.performed += instance.OnPointerPress;
                    @PointerPress.canceled += instance.OnPointerPress;
                    @PointerClick.started += instance.OnPointerClick;
                    @PointerClick.performed += instance.OnPointerClick;
                    @PointerClick.canceled += instance.OnPointerClick;
                }
            }
        }
        public WorldMapPlayActions @WorldMapPlay => new WorldMapPlayActions(this);

        // WorldMapPaused
        private readonly InputActionMap m_WorldMapPaused;
        private IWorldMapPausedActions m_WorldMapPausedActionsCallbackInterface;
        public struct WorldMapPausedActions
        {
            private @PlayerControls m_Wrapper;
            public WorldMapPausedActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
            public InputActionMap Get() { return m_Wrapper.m_WorldMapPaused; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(WorldMapPausedActions set) { return set.Get(); }
            public void SetCallbacks(IWorldMapPausedActions instance)
            {
                if (m_Wrapper.m_WorldMapPausedActionsCallbackInterface != null)
                {
                }
                m_Wrapper.m_WorldMapPausedActionsCallbackInterface = instance;
                if (instance != null)
                {
                }
            }
        }
        public WorldMapPausedActions @WorldMapPaused => new WorldMapPausedActions(this);

        // LevelsShared
        private readonly InputActionMap m_LevelsShared;
        private ILevelsSharedActions m_LevelsSharedActionsCallbackInterface;
        private readonly InputAction m_LevelsShared_ToggleMenu;
        public struct LevelsSharedActions
        {
            private @PlayerControls m_Wrapper;
            public LevelsSharedActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
            public InputAction @ToggleMenu => m_Wrapper.m_LevelsShared_ToggleMenu;
            public InputActionMap Get() { return m_Wrapper.m_LevelsShared; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(LevelsSharedActions set) { return set.Get(); }
            public void SetCallbacks(ILevelsSharedActions instance)
            {
                if (m_Wrapper.m_LevelsSharedActionsCallbackInterface != null)
                {
                    @ToggleMenu.started -= m_Wrapper.m_LevelsSharedActionsCallbackInterface.OnToggleMenu;
                    @ToggleMenu.performed -= m_Wrapper.m_LevelsSharedActionsCallbackInterface.OnToggleMenu;
                    @ToggleMenu.canceled -= m_Wrapper.m_LevelsSharedActionsCallbackInterface.OnToggleMenu;
                }
                m_Wrapper.m_LevelsSharedActionsCallbackInterface = instance;
                if (instance != null)
                {
                    @ToggleMenu.started += instance.OnToggleMenu;
                    @ToggleMenu.performed += instance.OnToggleMenu;
                    @ToggleMenu.canceled += instance.OnToggleMenu;
                }
            }
        }
        public LevelsSharedActions @LevelsShared => new LevelsSharedActions(this);

        // UI
        private readonly InputActionMap m_UI;
        private IUIActions m_UIActionsCallbackInterface;
        private readonly InputAction m_UI_Navigate;
        private readonly InputAction m_UI_Submit;
        private readonly InputAction m_UI_Cancel;
        private readonly InputAction m_UI_Point;
        private readonly InputAction m_UI_Click;
        private readonly InputAction m_UI_ScrollWheel;
        private readonly InputAction m_UI_MiddleClick;
        private readonly InputAction m_UI_RightClick;
        private readonly InputAction m_UI_TrackedDevicePosition;
        private readonly InputAction m_UI_TrackedDeviceOrientation;
        public struct UIActions
        {
            private @PlayerControls m_Wrapper;
            public UIActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
            public InputAction @Navigate => m_Wrapper.m_UI_Navigate;
            public InputAction @Submit => m_Wrapper.m_UI_Submit;
            public InputAction @Cancel => m_Wrapper.m_UI_Cancel;
            public InputAction @Point => m_Wrapper.m_UI_Point;
            public InputAction @Click => m_Wrapper.m_UI_Click;
            public InputAction @ScrollWheel => m_Wrapper.m_UI_ScrollWheel;
            public InputAction @MiddleClick => m_Wrapper.m_UI_MiddleClick;
            public InputAction @RightClick => m_Wrapper.m_UI_RightClick;
            public InputAction @TrackedDevicePosition => m_Wrapper.m_UI_TrackedDevicePosition;
            public InputAction @TrackedDeviceOrientation => m_Wrapper.m_UI_TrackedDeviceOrientation;
            public InputActionMap Get() { return m_Wrapper.m_UI; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(UIActions set) { return set.Get(); }
            public void SetCallbacks(IUIActions instance)
            {
                if (m_Wrapper.m_UIActionsCallbackInterface != null)
                {
                    @Navigate.started -= m_Wrapper.m_UIActionsCallbackInterface.OnNavigate;
                    @Navigate.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnNavigate;
                    @Navigate.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnNavigate;
                    @Submit.started -= m_Wrapper.m_UIActionsCallbackInterface.OnSubmit;
                    @Submit.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnSubmit;
                    @Submit.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnSubmit;
                    @Cancel.started -= m_Wrapper.m_UIActionsCallbackInterface.OnCancel;
                    @Cancel.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnCancel;
                    @Cancel.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnCancel;
                    @Point.started -= m_Wrapper.m_UIActionsCallbackInterface.OnPoint;
                    @Point.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnPoint;
                    @Point.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnPoint;
                    @Click.started -= m_Wrapper.m_UIActionsCallbackInterface.OnClick;
                    @Click.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnClick;
                    @Click.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnClick;
                    @ScrollWheel.started -= m_Wrapper.m_UIActionsCallbackInterface.OnScrollWheel;
                    @ScrollWheel.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnScrollWheel;
                    @ScrollWheel.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnScrollWheel;
                    @MiddleClick.started -= m_Wrapper.m_UIActionsCallbackInterface.OnMiddleClick;
                    @MiddleClick.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnMiddleClick;
                    @MiddleClick.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnMiddleClick;
                    @RightClick.started -= m_Wrapper.m_UIActionsCallbackInterface.OnRightClick;
                    @RightClick.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnRightClick;
                    @RightClick.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnRightClick;
                    @TrackedDevicePosition.started -= m_Wrapper.m_UIActionsCallbackInterface.OnTrackedDevicePosition;
                    @TrackedDevicePosition.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnTrackedDevicePosition;
                    @TrackedDevicePosition.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnTrackedDevicePosition;
                    @TrackedDeviceOrientation.started -= m_Wrapper.m_UIActionsCallbackInterface.OnTrackedDeviceOrientation;
                    @TrackedDeviceOrientation.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnTrackedDeviceOrientation;
                    @TrackedDeviceOrientation.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnTrackedDeviceOrientation;
                }
                m_Wrapper.m_UIActionsCallbackInterface = instance;
                if (instance != null)
                {
                    @Navigate.started += instance.OnNavigate;
                    @Navigate.performed += instance.OnNavigate;
                    @Navigate.canceled += instance.OnNavigate;
                    @Submit.started += instance.OnSubmit;
                    @Submit.performed += instance.OnSubmit;
                    @Submit.canceled += instance.OnSubmit;
                    @Cancel.started += instance.OnCancel;
                    @Cancel.performed += instance.OnCancel;
                    @Cancel.canceled += instance.OnCancel;
                    @Point.started += instance.OnPoint;
                    @Point.performed += instance.OnPoint;
                    @Point.canceled += instance.OnPoint;
                    @Click.started += instance.OnClick;
                    @Click.performed += instance.OnClick;
                    @Click.canceled += instance.OnClick;
                    @ScrollWheel.started += instance.OnScrollWheel;
                    @ScrollWheel.performed += instance.OnScrollWheel;
                    @ScrollWheel.canceled += instance.OnScrollWheel;
                    @MiddleClick.started += instance.OnMiddleClick;
                    @MiddleClick.performed += instance.OnMiddleClick;
                    @MiddleClick.canceled += instance.OnMiddleClick;
                    @RightClick.started += instance.OnRightClick;
                    @RightClick.performed += instance.OnRightClick;
                    @RightClick.canceled += instance.OnRightClick;
                    @TrackedDevicePosition.started += instance.OnTrackedDevicePosition;
                    @TrackedDevicePosition.performed += instance.OnTrackedDevicePosition;
                    @TrackedDevicePosition.canceled += instance.OnTrackedDevicePosition;
                    @TrackedDeviceOrientation.started += instance.OnTrackedDeviceOrientation;
                    @TrackedDeviceOrientation.performed += instance.OnTrackedDeviceOrientation;
                    @TrackedDeviceOrientation.canceled += instance.OnTrackedDeviceOrientation;
                }
            }
        }
        public UIActions @UI => new UIActions(this);

        // CommonHotkeys
        private readonly InputActionMap m_CommonHotkeys;
        private ICommonHotkeysActions m_CommonHotkeysActionsCallbackInterface;
        private readonly InputAction m_CommonHotkeys_Back;
        private readonly InputAction m_CommonHotkeys_Confirm;
        private readonly InputAction m_CommonHotkeys_NextSection;
        private readonly InputAction m_CommonHotkeys_PrevSection;
        private readonly InputAction m_CommonHotkeys_PickerNext;
        private readonly InputAction m_CommonHotkeys_PickerPrev;
        public struct CommonHotkeysActions
        {
            private @PlayerControls m_Wrapper;
            public CommonHotkeysActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
            public InputAction @Back => m_Wrapper.m_CommonHotkeys_Back;
            public InputAction @Confirm => m_Wrapper.m_CommonHotkeys_Confirm;
            public InputAction @NextSection => m_Wrapper.m_CommonHotkeys_NextSection;
            public InputAction @PrevSection => m_Wrapper.m_CommonHotkeys_PrevSection;
            public InputAction @PickerNext => m_Wrapper.m_CommonHotkeys_PickerNext;
            public InputAction @PickerPrev => m_Wrapper.m_CommonHotkeys_PickerPrev;
            public InputActionMap Get() { return m_Wrapper.m_CommonHotkeys; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(CommonHotkeysActions set) { return set.Get(); }
            public void SetCallbacks(ICommonHotkeysActions instance)
            {
                if (m_Wrapper.m_CommonHotkeysActionsCallbackInterface != null)
                {
                    @Back.started -= m_Wrapper.m_CommonHotkeysActionsCallbackInterface.OnBack;
                    @Back.performed -= m_Wrapper.m_CommonHotkeysActionsCallbackInterface.OnBack;
                    @Back.canceled -= m_Wrapper.m_CommonHotkeysActionsCallbackInterface.OnBack;
                    @Confirm.started -= m_Wrapper.m_CommonHotkeysActionsCallbackInterface.OnConfirm;
                    @Confirm.performed -= m_Wrapper.m_CommonHotkeysActionsCallbackInterface.OnConfirm;
                    @Confirm.canceled -= m_Wrapper.m_CommonHotkeysActionsCallbackInterface.OnConfirm;
                    @NextSection.started -= m_Wrapper.m_CommonHotkeysActionsCallbackInterface.OnNextSection;
                    @NextSection.performed -= m_Wrapper.m_CommonHotkeysActionsCallbackInterface.OnNextSection;
                    @NextSection.canceled -= m_Wrapper.m_CommonHotkeysActionsCallbackInterface.OnNextSection;
                    @PrevSection.started -= m_Wrapper.m_CommonHotkeysActionsCallbackInterface.OnPrevSection;
                    @PrevSection.performed -= m_Wrapper.m_CommonHotkeysActionsCallbackInterface.OnPrevSection;
                    @PrevSection.canceled -= m_Wrapper.m_CommonHotkeysActionsCallbackInterface.OnPrevSection;
                    @PickerNext.started -= m_Wrapper.m_CommonHotkeysActionsCallbackInterface.OnPickerNext;
                    @PickerNext.performed -= m_Wrapper.m_CommonHotkeysActionsCallbackInterface.OnPickerNext;
                    @PickerNext.canceled -= m_Wrapper.m_CommonHotkeysActionsCallbackInterface.OnPickerNext;
                    @PickerPrev.started -= m_Wrapper.m_CommonHotkeysActionsCallbackInterface.OnPickerPrev;
                    @PickerPrev.performed -= m_Wrapper.m_CommonHotkeysActionsCallbackInterface.OnPickerPrev;
                    @PickerPrev.canceled -= m_Wrapper.m_CommonHotkeysActionsCallbackInterface.OnPickerPrev;
                }
                m_Wrapper.m_CommonHotkeysActionsCallbackInterface = instance;
                if (instance != null)
                {
                    @Back.started += instance.OnBack;
                    @Back.performed += instance.OnBack;
                    @Back.canceled += instance.OnBack;
                    @Confirm.started += instance.OnConfirm;
                    @Confirm.performed += instance.OnConfirm;
                    @Confirm.canceled += instance.OnConfirm;
                    @NextSection.started += instance.OnNextSection;
                    @NextSection.performed += instance.OnNextSection;
                    @NextSection.canceled += instance.OnNextSection;
                    @PrevSection.started += instance.OnPrevSection;
                    @PrevSection.performed += instance.OnPrevSection;
                    @PrevSection.canceled += instance.OnPrevSection;
                    @PickerNext.started += instance.OnPickerNext;
                    @PickerNext.performed += instance.OnPickerNext;
                    @PickerNext.canceled += instance.OnPickerNext;
                    @PickerPrev.started += instance.OnPickerPrev;
                    @PickerPrev.performed += instance.OnPickerPrev;
                    @PickerPrev.canceled += instance.OnPickerPrev;
                }
            }
        }
        public CommonHotkeysActions @CommonHotkeys => new CommonHotkeysActions(this);
        private int m_KeyboardMouseSchemeIndex = -1;
        public InputControlScheme KeyboardMouseScheme
        {
            get
            {
                if (m_KeyboardMouseSchemeIndex == -1) m_KeyboardMouseSchemeIndex = asset.FindControlSchemeIndex("Keyboard&Mouse");
                return asset.controlSchemes[m_KeyboardMouseSchemeIndex];
            }
        }
        private int m_GamepadSchemeIndex = -1;
        public InputControlScheme GamepadScheme
        {
            get
            {
                if (m_GamepadSchemeIndex == -1) m_GamepadSchemeIndex = asset.FindControlSchemeIndex("Gamepad");
                return asset.controlSchemes[m_GamepadSchemeIndex];
            }
        }
        private int m_TouchSchemeIndex = -1;
        public InputControlScheme TouchScheme
        {
            get
            {
                if (m_TouchSchemeIndex == -1) m_TouchSchemeIndex = asset.FindControlSchemeIndex("Touch");
                return asset.controlSchemes[m_TouchSchemeIndex];
            }
        }
        public interface ITowerLevelPlayActions
        {
            void OnMoveShapeLeft(InputAction.CallbackContext context);
            void OnMoveShapeRight(InputAction.CallbackContext context);
            void OnRotateShapeUp(InputAction.CallbackContext context);
            void OnRotateShapeDown(InputAction.CallbackContext context);
            void OnFallSpeedUp(InputAction.CallbackContext context);
            void OnPointerFallSpeedUp(InputAction.CallbackContext context);
            void OnPointerPress(InputAction.CallbackContext context);
        }
        public interface ITowerLevelPausedActions
        {
        }
        public interface IWorldMapPlayActions
        {
            void OnDiscworldMovement(InputAction.CallbackContext context);
            void OnDiscworldZoom(InputAction.CallbackContext context);
            void OnPointerPress(InputAction.CallbackContext context);
            void OnPointerClick(InputAction.CallbackContext context);
        }
        public interface IWorldMapPausedActions
        {
        }
        public interface ILevelsSharedActions
        {
            void OnToggleMenu(InputAction.CallbackContext context);
        }
        public interface IUIActions
        {
            void OnNavigate(InputAction.CallbackContext context);
            void OnSubmit(InputAction.CallbackContext context);
            void OnCancel(InputAction.CallbackContext context);
            void OnPoint(InputAction.CallbackContext context);
            void OnClick(InputAction.CallbackContext context);
            void OnScrollWheel(InputAction.CallbackContext context);
            void OnMiddleClick(InputAction.CallbackContext context);
            void OnRightClick(InputAction.CallbackContext context);
            void OnTrackedDevicePosition(InputAction.CallbackContext context);
            void OnTrackedDeviceOrientation(InputAction.CallbackContext context);
        }
        public interface ICommonHotkeysActions
        {
            void OnBack(InputAction.CallbackContext context);
            void OnConfirm(InputAction.CallbackContext context);
            void OnNextSection(InputAction.CallbackContext context);
            void OnPrevSection(InputAction.CallbackContext context);
            void OnPickerNext(InputAction.CallbackContext context);
            void OnPickerPrev(InputAction.CallbackContext context);
        }
    }
}
